language: node_js
node_js:
- '6'
script:
- set -e
- npm run build
- npm run test-es5
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/pipez.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: P4av9VlKQ86uk2BVRn1P9LD2e3r9xYYb7uif8YE3ODOtXb6y0YsH5Xf+uBht94jQRLJBxbrs0sjcWqcbFdcHVr61e6wKRauJtvWz2MxasO43N8pTaowERROncOHNuckkJHv4w2lYHhJfiEBt1O4+GwHZkwIaJf/Gfhye2gX4f5R56EoQPMScqZXnSEQJjRqBnKjwKGDSJo75iBobEUKun4pge3oQcY4tVUmL4WQkfRYsuRotr2Fq8q/RzRrtluFMgPJJOely05McP70Y8Z8yC9JwFq2ImWCNCQowXQcwEx5tVrPox2vcKE9qPh2l3VcsalkcqtiBo0la2O7mCrQCVBg/sHUPuLNCzEx3OJzyleJr0daUxRf6b6DU9e8ztuy+TVwIkT9hiKv6/J3OsWNIbToBvHmlY+W4F8gh+9ZGTqkIK0DG7ejViLoX+Tzu1Zsw/lTlNq+Z2+HKleWUIwEBEayCV7/UKduQKsAKrIMS3ZrX+LOgg4BDF4G4rY8PPgnQ7Qkqj/nKknzzNhFoAmNyb/KjsCUsulcFmw3bNmsrcmhKKpYQGk7SSd+McK3vRbtZO87zPILquVdyVOpGfAk7/jwG6oxKkG4ndV85g+IiYgqfFwqmyRyy0lH/7Tz80r260QMgGBg+c7hGYlOvKRt/rNLMu+wyOnEKLVJqBftGnlc=
env:
  global:
  - secure: S7pgXNumvhPP6LjRVEND5TaCFi+gT2+OqxnJ2TXZ+OrtLNNzHlCtD5SoHazno7lrDCjeKpOy8BpscufWa3BcZK772WFcqKzTBm0D18RGWrWiLhLJrziXBA1/0lr7Hfu5EmeH/5Ly7aPeQ9PKI1aEwflnMFVxO/g/xH33OqBRg8JMt2/U0Fjrt86fAJ4TfNyYYyinhCpK4o8bb8SUM4Bg6qNk79d7QAOMYHRBfyddxHtoXpHBi+zlOy0PQ0mNANIudvjt/5oY9vhjnJsfr7rMDgzq02jT31w7YVdYHGoSR/pzRvB6IWWbOlT6J1crhCa76OfuxPPL2FJ8z6ROKVjwCJWhB1HXXyr6ddSWz7wSsSEeegFehY3ukJ71Q2y07uYU3EHCA7XkfmLO+7jzEYcs2ciQiBbdbmokeCRCw/redLX+8B4hlX+zJnT17C5/wQG/nh8UITeCTzTaAY1WIQ/ENXw48Y4g0SoeFILSND9vW5kWcG5I/8A9oKW9glpC87MflBZ/tiNKPbhK8A0u+K1qK0IjGkvToa0ug9tpzKrWNSnWI+bruRIsoeEx/I5q3ME52vEEYVdVXqp/oN9wp5XGJXcXuByQE3NO3a1p4qbaI30jh8JvcyYEBH7jxYjxToQlip3AyT0FiywsXaWQz+KJtwehS3xDt7a+sNDJ3NGIB24=
  - secure: EC7YtbZY7p1mHj0UVjOIbIzy3fcB1kHIXST5DeOEV9WykfKyKgA3Opt+9onl40TPnMhFb+sriSeCc18W3arV2z5tjHrk3Ck9GKMbsJ4CFGGAdp79LkDzI8q2z8HRJWkZHCEYOPdZ/relWMGScdB1oO10+ED/prH68XjKfMSdsoPFgElZt3zqOJ/4EWQSsT75/ivTEE0hxqXanUBSWp2tR739Wrktd90Vhmt9N5aLrBP1DdNwsAsdr8jlL7skVlgh1db7Tlgc9GoWrrbDMNQwmA+l/SgOO3qQpjaXSpWCBJ79fY0fNF2WE0hUJ11QO4KWRKaGagVeydVv2V437QXcaD5m5H/eLTGCX9VeAhu19O1yttwoOf6MuZ04kukPQskBYor4FjWrALIeT1/Ca9Mnoffq1qUre8xexEk9fkwDbIinqISjCdyxmsRxq0aPhwn0VZFetown/ni9R4IzFR7pQ5hkA/FScdfIl7BnMyY5iW7yqKQjvfLkMU7lp0ThyrJLK+pJ7haMKNW3aO6f6f6IBArZyq7In7VrGhkUuGja02ClUmAGndL6hyFWkaQf4GD2Fry4rMO57b3CUvZfzhWLkWc4Jmki/AlsDhrLMEOdGh4pmNffc8KbDA8cIajuEXvw+AVV+V8saD24DBx0G1DUadv42AayBieRO4pphtW7SMQ=
