language: node_js
node_js:
- '6'
script:
- set -e
- npm run build
- npm run test-es5
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/pipez.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: OBT9yLKwlSHlXP35EUEWF2b3Z4QVEKt7Iwp5xuisZ7jbT1Z+3C7HdWxrFqSEy9i+rarUto2MkHXOK+dpxo6MNPIhADXZ3xC8HED69/inwbjvqhea6J6hhG5gqtliB1RDfd1FhhPDMtJ/W7D31oyPdg6SW0U8PfTOlg+mO9CZ+OJm3L5bxGK9k3ko25TKrTHgtzt+FcXPX6zQ23EorfSFBlCLapFRRDxWWnZrpAQQ8XUQHe57jo2NflWopkRjxcyCiEG9B4RNMNUa4zdD/pXdFz3So35IyFQyoR3b5WwWZEYHl5zxjf8nj9HPCFHLQzx98CWai8Bn+O9mz5PJ/SsFCgl1q56OoZICXbooIPDdnpD8QJTzc6QQkGfjvsSfCIVxJwVrBissZ25XOaKhu+/7anTiWM9+3U1K8wMHw1cGa7+oSJL02zI3xXWoRsLrflWZqH94cJQq1m51WKDbfR80Ug0bT0rY5tEPzaAHtwe/Sv+exsBRlbj0wrL7FK+VjoXT5+S4H5EbTXw+dVtRtRMCv2eH0OYwf/M7t6Id3x7WygSqsR28gUAr02yQQn6G8OP+WVcJy7AbT+k2W9+22yYysTWjiaxJEXYA9Dwgdh+/t5rIRXR7LtoIhEL9DrnKO3OgS6xsd5BbpV9RSCFguBNqDGVe5h5n8H4IQIvu+e2nWCM=
env:
  global:
  - secure: S7pgXNumvhPP6LjRVEND5TaCFi+gT2+OqxnJ2TXZ+OrtLNNzHlCtD5SoHazno7lrDCjeKpOy8BpscufWa3BcZK772WFcqKzTBm0D18RGWrWiLhLJrziXBA1/0lr7Hfu5EmeH/5Ly7aPeQ9PKI1aEwflnMFVxO/g/xH33OqBRg8JMt2/U0Fjrt86fAJ4TfNyYYyinhCpK4o8bb8SUM4Bg6qNk79d7QAOMYHRBfyddxHtoXpHBi+zlOy0PQ0mNANIudvjt/5oY9vhjnJsfr7rMDgzq02jT31w7YVdYHGoSR/pzRvB6IWWbOlT6J1crhCa76OfuxPPL2FJ8z6ROKVjwCJWhB1HXXyr6ddSWz7wSsSEeegFehY3ukJ71Q2y07uYU3EHCA7XkfmLO+7jzEYcs2ciQiBbdbmokeCRCw/redLX+8B4hlX+zJnT17C5/wQG/nh8UITeCTzTaAY1WIQ/ENXw48Y4g0SoeFILSND9vW5kWcG5I/8A9oKW9glpC87MflBZ/tiNKPbhK8A0u+K1qK0IjGkvToa0ug9tpzKrWNSnWI+bruRIsoeEx/I5q3ME52vEEYVdVXqp/oN9wp5XGJXcXuByQE3NO3a1p4qbaI30jh8JvcyYEBH7jxYjxToQlip3AyT0FiywsXaWQz+KJtwehS3xDt7a+sNDJ3NGIB24=
